services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      # (แนะนำเปิด Basic Auth เพื่อป้องกัน UI)
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      # ใช้สำหรับเข้ารหัส Credentials ใน n8n (ต้องมีถึงจะบันทึก Credentials ได้)
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      # ---- Database (Render Free Postgres) ----
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # ตั้งค่าภายนอก (ถ้าต้องการให้ n8n สร้างลิงก์ Webhook ถูกต้อง)
      # สร้างหลังจากรู้โดเมนจริงแล้ว หรือแก้ไขใน Dashboard:
      # - key: WEBHOOK_URL
      #   value: https://<your-app>.onrender.com/
databases:
  - name: n8n-db
    plan: free
    databaseName: n8n
    user: n8n_user
